name: build
on:
  push:
    tags:
      - 'b*'

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'

      - run: |
          node npm-scripts postinstall

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload linux build
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./worker/out/Release/mediasoup-worker/mediasoup-worker
          asset_name: x64-lin-worker
          asset_content_type: application/octet-stream