name: build
on:
  push:

jobs:
  x64_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'

      - run: |
          node npm-scripts postinstall

      - uses: actions/upload-artifact@v2
        with:
          name: worker-release-windows
          path: ./worker/Release/lib/
  x64_linux:
    name: Build linux
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'

      - run: |
          node npm-scripts postinstall

      - uses: actions/upload-artifact@v2
        with:
          name: worker-release-linux
          path: ./worker/out/Release/*.a

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-18.04
    needs: [x64_linux, x64_windows]
    steps:
      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: worker-release-linux
          path: lin

      - name: Download windows artifacts
        uses: actions/download-artifact@v2
        with:
          name: worker-release-windows
          path: win

      - name: Zip artifacts
        run: |
          zip -r -j lin-lib lin/*
          zip -r -j win-lib win/*
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}

      - name: Upload windows static libraries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./win-lib.zip
          asset_name: win-lib.zip
          asset_content_type: application/zip

      - name: Upload linux static libraries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lin-lib.zip
          asset_name: lin-lib.zip
          asset_content_type: application/zip

  delete-artifacts:
    name: Delete artifacts
    runs-on: ubuntu-18.04
    needs: [create-release]
    if: ${{ always() }}
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            worker-release-windows
            worker-release-linux